version: '3'
services:

  # Nodejs
  dashboard-queue:
    image: dashboard-queue
    container_name: dashboard-queue
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      pelaporan_dashboard-queue_network:
    restart: always
    volumes:
      - .:/usr/apps/jds/express-dashboard-queue
      - /usr/apps/jds/express-dashboard-queue/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"

#Docker Networks
networks:
  pelaporan_dashboard-queue_network:
    driver: bridge
